name: Load Test

on:
  push:
    branches:
      - master

jobs:
  load_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C780D0BDB1A69C86
            echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
            sudo apt-get update
            sudo apt-get install -y k6

      - name: Run load test
        id: load_test
        run: |
          wget -O loadtest.js https://raw.githubusercontent.com/MarcHedeby/k6WtfWorkPipelineBullshit/master/loadtest.js
          k6 run loadtest.js
        continue-on-error: true  # Continue to the next step even if the load test fails

      - name: Run stress test
        if: steps.load_test.outcome == 'success'  # Only run if the load test was successful
        run: |
          wget -O stress_test.js https://raw.githubusercontent.com/MarcHedeby/k6WtfWorkPipelineBullshit/master/bygspy%20k6%20test/stress_test.js
          k6 run stress_test.js

      - name: Check if tests failed
        if: steps.load_test.outcome == 'failure' || steps.stress_test.outcome == 'failure'  # Only run if either load or stress test failed
        run: exit 1  # Exit with a non-zero code to indicate failure, preventing pushing

      - name: Push changes
        if: steps.load_test.outcome == 'success' && steps.stress_test.outcome == 'success'  # Only push changes if both tests were successful
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Automated test passed"
          git push
