name: Load Test

on:
  push:
    branches:
      - master

jobs:
  load_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          curl -L https://github.com/loadimpact/k6/releases/download/v0.34.0/k6-v0.34.0-linux64.tar.gz | tar xz
          sudo mv k6-v0.34.0-linux64/k6 /usr/local/bin/k6

      - name: Run load test
        run: k6 run path/to/your/loadtest.js
