name: Run Pipeline
on:
  push:
    branches:
      - master

jobs:
  performance_test:
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
            Invoke-WebRequest -Uri 'https://dl.k6.io/msi/k6-v0.50.0-amd64.msi' -OutFile k6.msi
            Start-Process msiexec.exe -Wait -ArgumentList '/i', 'k6.msi', '/quiet'

      - name: Run k6 script in Git Bash
        run: |
          bash -c "C:\\Program Files\\k6\\k6 run C:\\work\\bygspy\\k6\\test\\loadtest.js"


